### ISSUE TITLE
Missing data in columns: Methy.std.

### ISSUE THREAD

**Issue by BastienNguyen** [YinanZheng/REMP#1]
Hello,

For some unclear reason when I try to apply the remp function it stuck on specific samples whith the following error message;

`Predicting sample TCGA-55-6983 ...
    TCGA-55-6983 completed! 193 sample(s) left ...  (451 sec.)
Predicting sample TCGA-55-7227 ...
Error: Missing data in columns: Methy.std.`

Thanks for your help,

Bastien

**Comment by YinanZheng** [comment]
This is odd. Did you try the latest version? (current BioC release v1.8.1). Also make sure your `ranger` package is also the latest. 

It would be also helpful if you can provide the code you used.
