### ISSUE TITLE
 knnimp.internal error

### ISSUE THREAD

**Issue by yeswzc** [YinanZheng/REMP#2]
Hi Yinan,
I am using REMP to impute [TCGA LUAD 450 methylation data](https://tcga.xenahubs.net/download/TCGA.LUAD.sampleMap/HumanMethylation450.gz). I tried to impute DNA methylation data after filtered probes with missing raio > 20%. However, an error occured:
``
Error in knnimp.internal(x, k, imiss, irmiss, p, n, maxp = maxp) :
  NA/NaN/Inf in foreign function call (arg 1)
Calls: grooMethy -> <Anonymous> -> knnimp -> knnimp.internal
Execution halted
``
Do you know what is happens, and how to solve it?

Thanks!

**Comment by YinanZheng** [comment]
I could not replicate your error. Please see my code and verbose message. Hope it is helpful.

```
dat <- read.table(file = "./HumanMethylation450", header = TRUE, sep = "\t", row.names = 1)
missing_ind <- which(rowMeans(is.na(dat)) > 0.2)
dat_sub <- dat[-missing_ind,]

dat_groom <- grooMethy(dat_sub, verbose = TRUE)
```

Illumina 450k Methylation data in beta value detected.
A total of 16357 zero beta values are found.
    Fixing 'zero' beta values with the smallest non-0 beta value = 1e-04 ...
    A total of 9116 one beta values are found.
    Fixing 'one' beta values with the largest non-1 beta value = 0.9999 ...
    A total of 120318 NA/NaN/Inf values are found.
    Converting beta/percentage value to M value ...
    Imputing missing values using KNN method ...
    All imputed probes are within the original data range.
 Methylation data grooming is completed.  (189 sec.)

**Comment by yeswzc** [comment]
Hi, I was using R version 3.5 which gave the error. I tested again using R version 3.5, this time it worked.
Thank you!
