### ISSUE TITLE
EPIC array REMP run

### ISSUE THREAD

**Issue by krissaMAC** [YinanZheng/REMP#3]
Hi Yinan,

I am using the REMP package and the test run worked perfectly.
However when I try to use my data (EPIC array) I get the following error:

> remp.res <- remp(Meth_450k,
+                  REtype = 'Alu',
+                  parcel = remparcel,
+                  ncore = 1,
+                  seed = 777)
Using random seed = 777
Error in impute::impute.knn(t(mdata)) : 
  a column has more than 80 % missing values!
In addition: Warning message:
In if (minfi::preprocessMethod(methyDat_work) == "grooMethy(REMP)") { :
  the condition has length > 1 and only the first element will be used

> class(Meth_450k)
[1] "RatioSet"
attr(,"package")
[1] "minfi"
> Meth_450k
class: RatioSet 
dim: 866091 2 
metadata(0):
assays(2): Beta M
rownames(866091): cg18478105 cg09835024 ... cg10633746 cg12623625
rowData names(0):
colnames(2): 202274990120_R01C01 202274990120_R02C01
colData names(9): Sample_Name Sample_Well ... Basename filenames
Annotation
  array: IlluminaHumanMethylationEPIC
  annotation: ilm10b4.hg19
Preprocessing
  Method: Raw (no normalization or bg correction)
  minfi version: 1.36.0
  Manifest version: 0.3.0

what would be the next step?
thank you
Cristina

**Comment by YinanZheng** [comment]
Hi Cristina @krissaMAC ,

Some CpGs have too much missing data, which prevents the imputation from running. You can try to remove any CpGs with more than 80% missing data before feeding the dataset to remp().

Let me know if this helps. 

Thanks!

Yinan

**Comment by krissaMAC** [comment]
Hi Yinan,

Thank. You for your note. I have done that and it works better!
I am having problem with the annotation portion (see below)
remp.res <- decodeAnnot(remp.res, type = "symbol")

The task never finishes … it works fine with the test data. I am only running a samples to test it.
Would you let me know what I should try next?

Thanks
Cristina


From: Yinan Zheng ***@***.***>
Reply-To: YinanZheng/REMP ***@***.***>
Date: Monday, March 29, 2021 at 1:09 PM
To: YinanZheng/REMP ***@***.***>
Cc: "Miranda de Araujo Correia, Maria Cristina (Cristina), Ph.D." ***@***.***>, Mention ***@***.***>
Subject: [EXTERNAL] Re: [YinanZheng/REMP] EPIC array REMP run (#3)


Hi Cristina @krissaMAC<https://github.com/krissaMAC> ,

Some CpGs have too much missing data, which prevents the imputation from running. You can try to remove any CpGs with more than 80% missing data before feeding the dataset to remp().

Let me know if this helps.

Thanks!

Yinan

**Comment by YinanZheng** [comment]
Hi Cristina @krissaMAC,

Yes, this step takes some time, especially for EPIC array. You can allow parallel computing by adding the "ncore" parameter (default ncore =1, i.e., no parallel computing)

For example:

decodeAnnot(remp.res, type = "symbol", ncore = 4) #assume you have a 4-core CPU

Best,
Yinan
